### Site info:
title: LSDCodingBlog
tagline: Posts about the LSDTopoTools code. 
author: Simon M. Mudd and theLSDTopoTools team. 
email: simon.m.mudd@ed.ac.uk
description: "LSDCodingBlog. Useful for a vanishingly small number of people." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "c++, python, topographic analysis, Land Surface Dynamics, Geosciences, geomorphology, landscape evolution"
baseurl: "/LSDCodingBlog" # the subpath of your site, e.g. /blog
url: "https://LSDtopotools.github.io/LSDCodingBlog" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: LSDTopoToolbox
github_username:  LSDtopotools
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Lijia Yu. I made the Freshman21 theme. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: https://avatars2.githubusercontent.com/u/13199251?v=3&s=200 # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: LSDTopoTools
      href: http://LSDtopotools.github.io
      title: Coding notes
    - name: LSDTopoTools homepage
      href: http://LSDtopotools.github.io
      title: LSDTopoTools homepage


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
